name    'AlexCline-fstab'
version '0.5.3'
author 'Alex Cline <alex.cline@gmail.com>'
license 'Apache License, Version 2.0'
summary 'The fstab module helps puppet manage entries in fstab.'
description 'The fstab module helps puppet manage entries in fstab.'
project_page 'https://github.com/AlexCline/fstab'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
